# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh_account', '0002_auto_20161026_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='oauth_secret',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='oauth_token',
        ),
    ]
