# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-15 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('PICKUP', 'Pick up Game'), ('MENS LEAGUE', 'Mens League')], default='PICKUP', max_length=15)),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recurring', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Games',
                'ordering': ('starttime',),
            },
        ),
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('map', models.ImageField(null=True, upload_to='')),
                ('gmap_url', models.CharField(max_length=200, null=True)),
                ('skatesharpen', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Rinks',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='game',
            name='rink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametime.Rink'),
        ),
    ]
