# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rink',
            name='slug',
            field=models.SlugField(default='ab', unique=True),
            preserve_default=False,
        ),
    ]
