# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-15 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='playerlist',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
