# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-15 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('starttime',), 'verbose_name': 'Game'},
        ),
        migrations.AlterModelOptions(
            name='rink',
            options={'ordering': ('name',), 'verbose_name': 'Rink'},
        ),
        migrations.AlterField(
            model_name='rink',
            name='gmap_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rink',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rink',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
