# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-15 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0002_auto_20170815_2328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
            ],
        ),
    ]
