# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-05 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gametime', '0003_auto_20170823_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlayerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('customlist', models.ManyToManyField(blank=True, null=True, related_name='custom_list', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Player List',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='playerlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='playerlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
