# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='league',
            field=models.CharField(blank=True, choices=[('HOUSE LEAGUE', 'House League.'), ('TRAVEL LEAGUE', 'Travel League.'), ('JUNIORS', 'Juniors.'), ('COLLEGE', 'College.'), ('MAJOR JUNIORS', 'Major Juniors.'), ('PROFESSIONAL', 'Professional.')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('WING', 'Wing.'), ('CENTER', 'Center.'), ('DEFENSE', 'Defense.')], max_length=8),
        ),
    ]
