# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='oauth_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
