# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-21 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhockeyUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='league',
            field=models.CharField(blank=True, choices=[('HOUSE LEAGUE', 'House League'), ('TRAVEL LEAGUE', 'Travel League'), ('JUNIORS', 'Juniors'), ('COLLEGE', 'College'), ('MAJOR JUNIORS', 'Major Juniors'), ('PROFESSIONAL', 'Professional')], max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('WING', 'Wing'), ('CENTER', 'Center'), ('DEFENSE', 'Defense')], max_length=8),
        ),
    ]
