# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-21 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhockeyUser', '0002_auto_20161221_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
