# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-05 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhockeyUser', '0004_auto_20170228_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
